name: Push new tag

on:
  schedule:
    # every 1st of the month
    - cron:  '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: push tag
        run: ./push-tag.sh
